version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    container_name: es
    environment:
      - cluster.name=es-cluster
      - node.name=master
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      # disabling xpack since we don't use it and it installed by default in this image
      # ES v6 contains -OSS alternatives that don't contain xpack
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false

      - http.host=0.0.0.0
      - network.host=0.0.0.0
      - http.port=9200
      - transport.host=127.0.0.1
      - http.compression=true
      # - network.publish_host=172.20.5.193
      # - transport.tcp.port=9300
      # - transport.bind_host=_eth0_
      # - discovery.zen.ping.unicast.hosts=172.20.5.193:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    networks:
      esnet:
        aliases:
          - 'es'    

  cerebro:
    image: lmenezes/cerebro:0.8.1
    container_name: cerebro
    ports:
      - 9000:9000
    networks:
      esnet:
        aliases:
          - 'cerebro'

  redis: 
    image: redis:5.0.1-alpine
    container_name: redis
    ports:
      - 6379:6379
    networks:
      esnet:
        aliases:
          - 'redis'
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redisdata:/data
    entrypoint: redis-server --appendonly yes

volumes:
  esdata:
  redisdata:

networks:
   esnet:
